services:
  server:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_AUTH_TOKEN: ${DATABASE_AUTH_TOKEN}
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_AUTH_TOKEN: ${DATABASE_AUTH_TOKEN}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      INSTAPAPER_OAUTH_ID: ${INSTAPAPER_OAUTH_ID}
      INSTAPAPER_OAUTH_SECRET: ${INSTAPAPER_OAUTH_SECRET}
    ports:
      - 3000:3000
