services:
  server:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_AUTH_TOKEN: ${DATABASE_AUTH_TOKEN}
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_AUTH_TOKEN: ${DATABASE_AUTH_TOKEN}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      UPSTASH_REDIS_REST_URL: ${UPSTASH_REDIS_REST_URL}
      UPSTASH_REDIS_REST_TOKEN: ${UPSTASH_REDIS_REST_TOKEN}
      FROM_EMAIL_ADDRESS: ${FROM_EMAIL_ADDRESS}
      RESEND_API_KEY: ${RESEND_API_KEY}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      VITE_PUBLIC_SUPPORT_EMAIL_ADDRESS: ${VITE_PUBLIC_SUPPORT_EMAIL_ADDRESS}
      INSTAPAPER_OAUTH_ID: ${INSTAPAPER_OAUTH_ID}
      INSTAPAPER_OAUTH_SECRET: ${INSTAPAPER_OAUTH_SECRET}
    ports:
      - 3000:3000
