/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AuthRouteImport } from './app/auth'
import { Route as HomeRouteImport } from './app/_home'
import { Route as AppRouteImport } from './app/_app'
import { Route as AppIndexRouteImport } from './app/_app.index'
import { Route as AuthSignUpRouteImport } from './app/auth.sign-up'
import { Route as AuthSignInRouteImport } from './app/auth.sign-in'
import { Route as AuthResetRouteImport } from './app/auth.reset'
import { Route as AppImportRouteImport } from './app/_app.import'
import { Route as AppWatchIdRouteImport } from './app/_app.watch.$id'
import { Route as AppReadIdRouteImport } from './app/_app.read.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchIdRoute = AppWatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReadIdRoute = AppReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/import': typeof AppImportRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AppIndexRoute
  '/read/$id': typeof AppReadIdRoute
  '/watch/$id': typeof AppWatchIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/import': typeof AppImportRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AppIndexRoute
  '/read/$id': typeof AppReadIdRoute
  '/watch/$id': typeof AppWatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_home': typeof HomeRoute
  '/auth': typeof AuthRouteWithChildren
  '/_app/import': typeof AppImportRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/read/$id': typeof AppReadIdRoute
  '/_app/watch/$id': typeof AppWatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/import'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/read/$id'
    | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/import'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/read/$id'
    | '/watch/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_home'
    | '/auth'
    | '/_app/import'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_app/'
    | '/_app/read/$id'
    | '/_app/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  HomeRoute: typeof HomeRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/watch/$id': {
      id: '/_app/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof AppWatchIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/read/$id': {
      id: '/_app/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof AppReadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppImportRoute: typeof AppImportRoute
  AppIndexRoute: typeof AppIndexRoute
  AppReadIdRoute: typeof AppReadIdRoute
  AppWatchIdRoute: typeof AppWatchIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppImportRoute: AppImportRoute,
  AppIndexRoute: AppIndexRoute,
  AppReadIdRoute: AppReadIdRoute,
  AppWatchIdRoute: AppWatchIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthResetRoute: typeof AuthResetRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetRoute: AuthResetRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  HomeRoute: HomeRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
